# Generated by Django 6.0.7 on 2026-08-20 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_number', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('course_name', models.CharField(blank=True, null=True)),
                ('grade_level', models.CharField(blank=True, max_length=50, null=True)),
                ('credits', models.CharField(blank=True, null=True)),
                ('length', models.CharField(blank=True, max_length=50, null=True)),
                ('essential_skills', models.TextField(blank=True, null=True)),
                ('prerequisite_courses', models.TextField(blank=True, null=True)),
                ('concurrent', models.TextField(blank=True, null=True)),
                ('AP_honors', models.TextField(blank=True, null=True)),
                ('section', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('work_outside_of_class', models.TextField(blank=True, null=True)),
                ('rop', models.TextField(blank=True, null=True)),
                ('school_site', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
