# Generated by Django 6.0.7 on 2026-08-23 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathway_app', '0002_alter_course_course_name_alter_course_credits_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='completed_courses',
        ),
        migrations.CreateModel(
            name='StudentCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_level', models.IntegerField(choices=[(9, '9th Grade'), (10, '10th Grade'), (11, '11th Grade'), (12, '12th Grade')], default=9)),
                ('semesters', models.CharField(blank=True, default='1', max_length=10, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pathway_app.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pathway_app.studentprofile')),
            ],
            options={
                'unique_together': {('student', 'course')},
            },
        ),
    ]
