# Generated by Django 6.0.7 on 2026-08-23 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathway_app', '0003_remove_studentprofile_completed_courses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='completed_courses',
            field=models.ManyToManyField(blank=True, through='pathway_app.StudentCourse', to='pathway_app.course'),
        ),
    ]
