# Generated by Django 6.0.7 on 2026-08-23 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathway_app', '0004_studentprofile_completed_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='prerequisite_courses',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
