# Generated by Django 6.0.7 on 2026-08-23 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathway_app', '0005_alter_course_prerequisite_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcourse',
            name='is_pre_hs',
            field=models.BooleanField(default=False),
        ),
    ]
