# Generated by Django 6.0.7 on 2026-08-23 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathway_app', '0006_studentcourse_is_pre_hs'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcourse',
            name='is_summer',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='studentcourse',
            name='is_pre_hs',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
