# Generated by Django 6.0.7 on 2026-08-23 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathway_app', '0007_studentcourse_is_summer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcourse',
            name='grade_level',
            field=models.IntegerField(choices=[(9, '9th Grade'), (10, '10th Grade'), (11, '11th Grade'), (12, '12th Grade')], default=9, null=True),
        ),
    ]
