# Generated by Django 6.0.7 on 2026-09-07 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathway_app', '0008_alter_studentcourse_grade_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcourse',
            name='sports_grades',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
