# Generated by Django 6.0.7 on 2026-09-07 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathway_app', '0009_studentcourse_sports_grades'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentcourse',
            name='sports_grades',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='sports_grades',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
