# Generated by Django 6.0.7 on 2026-09-11 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathway_app', '0010_remove_studentcourse_sports_grades_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcourse',
            name='is_overridden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentcourse',
            name='override_error_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
