# Generated by Django 6.0.7 on 2026-09-12 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathway_app', '0011_studentcourse_is_overridden_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pathway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PathwayCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(help_text='Position of the course in this pathway (e.g., Level 1, Level 2)')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pathway_links', to='pathway_app.course')),
                ('pathway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pathway_courses', to='pathway_app.pathway')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('pathway', 'course')},
            },
        ),
        migrations.AddField(
            model_name='pathway',
            name='courses',
            field=models.ManyToManyField(related_name='pathways', through='pathway_app.PathwayCourse', to='pathway_app.course'),
        ),
    ]
