# Generated by Django 6.0.7 on 2026-09-12 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathway_app', '0012_pathway_pathwaycourse_pathway_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathway',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pathway_images/'),
        ),
    ]
