# Generated by Django 6.0.7 on 2026-09-12 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathway_app', '0013_pathway_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicPathway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='academic_pathway_images/')),
            ],
        ),
        migrations.CreateModel(
            name='AcademicPathwayCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(help_text='Position of the course in this academic pathway (e.g., Level 1, Level 2)')),
                ('academic_pathway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_pathway_courses', to='pathway_app.academicpathway')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_pathway_links', to='pathway_app.course')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('academic_pathway', 'course')},
            },
        ),
        migrations.AddField(
            model_name='academicpathway',
            name='courses',
            field=models.ManyToManyField(related_name='academic_pathways', through='pathway_app.AcademicPathwayCourse', to='pathway_app.course'),
        ),
    ]
