# Generated by Django 6.0.7 on 2026-09-12 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathway_app', '0014_academicpathway_academicpathwaycourse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicpathway',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
