# Generated by Django 6.0.7 on 2026-09-12 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathway_app', '0015_alter_academicpathway_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicpathway',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='academic_pathway_images/'),
        ),
    ]
