# Generated by Django 6.0.7 on 2026-09-12 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathway_app', '0017_alter_academicpathway_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicpathway',
            name='image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
