# Generated by Django 6.0.7 on 2026-09-12 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pathway_app', '0018_alter_academicpathway_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academicpathway',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='academicpathway',
            name='description',
        ),
        migrations.DeleteModel(
            name='AcademicPathwayCourse',
        ),
    ]
