# Generated by Django 6.0.7 on 2026-09-12 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathway_app', '0019_remove_academicpathway_courses_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='academicpathway',
            old_name='image',
            new_name='image1',
        ),
        migrations.AddField(
            model_name='academicpathway',
            name='image2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
