# Generated by Django 6.0.7 on 2026-09-20 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathway_app', '0020_rename_image_academicpathway_image1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='grad_year',
            field=models.TextField(blank=True, null=True),
        ),
    ]
